# Generated by Django 4.2.21 on 2025-08-06 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 1, 23, 0)),
            preserve_default=False,
        ),
    ]
