# Generated by Django 3.0.1 on 2025-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20250518_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='what_three_words_link',
            field=models.URLField(),
        ),
    ]
