# Generated by Django 3.0.1 on 2025-05-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='about_section',
        ),
    ]
