# Generated by Django 4.2.21 on 2025-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_teammember_id_alter_whoweare_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='text',
            field=models.TextField(),
        ),
    ]
