# Generated by Django 4.2.21 on 2025-06-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_whoweare_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whoweare',
            options={'verbose_name': 'Who We Are', 'verbose_name_plural': 'Who We Are'},
        ),
    ]
