# Generated by Django 3.0.1 on 2025-05-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='amount_of_time',
            new_name='amount_of_time_hours',
        ),
    ]
