# Generated by Django 3.0.1 on 2025-05-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20250503_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='table',
            field=models.ForeignKey(default='table_1', on_delete=django.db.models.deletion.CASCADE, to='bookings.Table'),
            preserve_default=False,
        ),
    ]
