# Generated by Django 3.0.1 on 2025-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_timeslot_dummy_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='table',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(editable=False),
        ),
    ]
