# Generated by Django 3.0.1 on 2025-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20250504_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dummy_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
