# Generated by Django 3.0.1 on 2025-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20250504_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='extra_field',
            field=models.CharField(default='temp', max_length=10),
        ),
    ]
