# Generated by Django 3.0.1 on 2025-05-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_table_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dummy_field',
        ),
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
