# Generated by Django 4.2.21 on 2025-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_id_alter_table_id_alter_timeslot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='seats_available',
            field=models.PositiveIntegerField(default=68),
        ),
    ]
