# Generated by Django 4.2.21 on 2025-06-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_table_seats_required_timeslot_seats_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='seats_available',
        ),
        migrations.CreateModel(
            name='SlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_available', models.PositiveIntegerField(default=68)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot')),
            ],
            options={
                'unique_together': {('date', 'timeslot')},
            },
        ),
    ]
