# Generated by Django 4.2.21 on 2025-06-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_timeslot_seats_available_slotavailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
