# Generated by Django 4.2.21 on 2025-06-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='private_hire',
            field=models.BooleanField(default=False),
        ),
    ]
