# Generated by Django 4.2.21 on 2025-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_table_private_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotavailability',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
