# Generated by Django 4.2.21 on 2025-06-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_slotavailability_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotavailability',
            old_name='is_blocked',
            new_name='is_blocked_for_hire',
        ),
    ]
