# Generated by Django 4.2.21 on 2025-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_email_booking_name_booking_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotavailability',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
